// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtRK2n64dlEdqdbiNjPUksl28Ia19qZt0',
    appId: '1:688514171612:web:235ea689e97a984ceaaa19',
    messagingSenderId: '688514171612',
    projectId: 'travelling-brandr-art',
    authDomain: 'travelling-brandr-art.firebaseapp.com',
    storageBucket: 'travelling-brandr-art.firebasestorage.app',
    measurementId: 'G-P4TH0N7VCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWE58i_8tKAQZP5vXuSV-GA7QjcWgsAo',
    appId: '1:688514171612:android:1a07e47485083e9beaaa19',
    messagingSenderId: '688514171612',
    projectId: 'travelling-brandr-art',
    storageBucket: 'travelling-brandr-art.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC7ynUzbHRo7oI5KAP_zhU__uxl13QjzQ',
    appId: '1:688514171612:ios:4e990da08f178053eaaa19',
    messagingSenderId: '688514171612',
    projectId: 'travelling-brandr-art',
    storageBucket: 'travelling-brandr-art.firebasestorage.app',
    iosBundleId: 'com.therapy.traveling.traveling',
  );
}
